#!/bin/sh

### BEGIN INIT INFO
# Provides:               hsn2-data-store
# Required-Start:
# Required-Stop:
# Default-Start:          2 3 4 5
# Default-Stop:           0 1 6
# Short-Description:      Start/Stop the HSN2 Data Store
# Description:            Start/Stop the HSN2 Data Store daemon.
### END INIT INFO

if [ -z "`which java`" ]; then
	echo "JAVA need to be installed first!"
	exit 1
fi

. /lib/lsb/init-functions

NAME="HSN2 Data Store"
HSN2_COMPONENT="data-store"

HSN2_COMPONENT_HOME="/usr/share/hsn2/$HSN2_COMPONENT"
PIDFILE="/var/run/hsn2-$HSN2_COMPONENT.pid"

HSN2_COMPONENT_PARAMS=""

case "$1" in
	start)
		log_daemon_msg "Starting" "$NAME"
		cd "$HSN2_COMPONENT_HOME"
		start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --exec $HSN2_COMPONENT_HOME/$HSN2_COMPONENT.sh -- $HSN2_COMPONENT_PARAMS
		sleep 1
		PID=`cat $PIDFILE`
		TEST=`ps ax | grep $PID | grep java | sed -e 's/^ *//' | cut -d' ' -f1`
		if [ -n "$TEST" ]; then
			log_end_msg 0
		else
			log_end_msg 1
			echo "" > $PIDFILE
		fi
		;;

	stop)
		log_daemon_msg "Stopping" "$NAME"
		if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
			log_end_msg 0
			echo "" > $PIDFILE
			#rm -f $PIDFILE
		else
			log_end_msg 1
		fi
		;;

	status)
		status_of_proc -p $PIDFILE "$JAVA" "$NAME" && exit 0 || exit $?
		;;
esac
exit 0
